### ISSUE TITLE
"TypeError: POt.indexOf is not a function" with mode: text and type: scattergl

### ISSUE THREAD

**Issue by WeisSeb** [plotly/plotly.js#7353]
After upgrading to v3.0.0 Plotly.js throws an error when trying to plot some text in a scattergl plot e.g:

```
import * as Plotly from 'plotly.js-dist-min'

var element = document.getElementById('plot');

Plotly.newPlot(element, [{
    type: 'scattergl',
    x: [1,3],
    y: [1,3],
    text: "some text",
    mode: "text"
},], {
    margin: {t: 0}
}, {});
```

causes the following error to appear in the browser console and nothing is plotted. Axes do however still appear
```
plotly__js-dist-min.js?v=ea4ace4f:60842 Uncaught TypeError: POt.indexOf is not a function
    at Object.bqe [as parse] (plotly__js-dist-min.js?v=ea4ace4f:60842:21)
    at plotly__js-dist-min.js?v=ea4ace4f:64366:25
    at Array.forEach (<anonymous>)
    at Vu.update (plotly__js-dist-min.js?v=ea4ace4f:64362:71)
    at new Vu (plotly__js-dist-min.js?v=ea4ace4f:64264:51)
    at bOe.exports [as plot] (plotly__js-dist-min.js?v=ea4ace4f:64540:363)
    at Kve (plotly__js-dist-min.js?v=ea4ace4f:21173:93)
    at yv.plot (plotly__js-dist-min.js?v=ea4ace4f:21149:17)
    at ld.drawData (plotly__js-dist-min.js?v=ea4ace4f:16265:77)
    at li.syncOrAsync (plotly__js-dist-min.js?v=ea4ace4f:7233:63)
```

Other text modes, e.g. "mode:text+markers" have the same issue. This error does not occur if type is defined as "scatter"

This did work in previous versions

**Comment by secretwpn** [comment]
Same happens here. Sadly we can't use this version until fixed.

**Comment by ayjayt** [comment]
Here's the detailed trace (I don't have source map, so its the bundle):

```
  var require_css_system_font_keywords = __commonJS({
    "node_modules/css-system-font-keywords/index.json"() {
    }
```

as called by ["node_modules/css-font/parse.js"](https://github.com/dy/css-font) in 

```
      var systemFontKeywords = require_css_system_font_keywords();
```

Which then uses `indexOf` to search `systemFontKeywords`.

That css-system-font-kewords/index.json` is resolving as `{}`, not `[...]` [like it should be](https://github.com/jednano/css-system-font-keywords/blob/master/index.json). It is clearly meant to resolve as `[...]` because it is defined that way and because its converted explicitly from `[]` to `{}` later. 

So, a couple theories:

- That json file didn't get bundled into 3.0.0 for some reason and it default as `{}`.
- It hasn't been loading for a while and the default has changed from `[]` to `{}` (less likely).

Leaning towards the first.

**Comment by secretwpn** [comment]
Still an issue in `v3.0.3` and `v3.1.0-rc.0`

Interesting that not many people complain about that, since scattergl + texts is completely unusable as is.

**Comment by tommyltk** [comment]
May I know when this will be fixed?  Or any workaround?
Current workaround is to use 2.35.2.

**Comment by tommyltk** [comment]
Any update on the fix?

**Comment by secretwpn** [comment]
@tommyltk there is no point asking when it will be fixed. 
This is not how github works, plotly.js is an opensource product available to us for free. 
It seems the team behind plotly is really short of resources and can't afford prioritizing this specific issue to be fixed timely. 

One of us can always fix it himself and propose the fix to the main repo. This is probably the only way to speed up the process.

If your comment does not bring valuable information (e.g. about the issue being active in the specific version or a potential clue to the reason behind the issue) it is better to just subscribe to the issue, hit the reaction on the original post and then gather some patience and wait (or look for another library / own development) which sadly seems like the most probable way for my project.

If you don't specifically need some feature or fix available in 3.x - you can still use the older 2.x version - it does not suffer from this issue

**Comment by emilykl** [comment]
I am investigating this issue.
