### PR TITLE
Fix issue causing empty ScatterGL plots when using text elements 

### LINKED ISSUE #7353: "TypeError: POt.indexOf is not a function" with mode: text and type: scattergl
After upgrading to v3.0.0 Plotly.js throws an error when trying to plot some text in a scattergl plot e.g:

```
import * as Plotly from 'plotly.js-dist-min'

var element = document.getElementById('plot');

Plotly.newPlot(element, [{
    type: 'scattergl',
    x: [1,3],
    y: [1,3],
    text: "some text",
    mode: "text"
},], {
    margin: {t: 0}
}, {});
```

causes the following error to appear in the browser console and nothing is plotted. Axes do however still appear
```
plotly__js-dist-min.js?v=ea4ace4f:60842 Uncaught TypeError: POt.indexOf is not a function
    at Object.bqe [as parse] (plotly__js-dist-min.js?v=ea4ace4f:60842:21)
    at plotly__js-dist-min.js?v=ea4ace4f:64366:25
    at Array.forEach (<anonymous>)
    at Vu.update (plotly__js-dist-min.js?v=ea4ace4f:64362:71)
    at new Vu (plotly__js-dist-min.js?v=ea4ace4f:64264:51)
    at bOe.exports [as plot] (plotly__js-dist-min.js?v=ea4ace4f:64540:363)
    at Kve (plotly__js-dist-min.js?v=ea4ace4f:21173:93)
    at yv.plot (plotly__js-dist-min.js?v=ea4ace4f:21149:17)
    at ld.drawData (plotly__js-dist-min.js?v=ea4ace4f:16265:77)
    at li.syncOrAsync (plotly__js-dist-min.js?v=ea4ace4f:7233:63)
```

Other text modes, e.g. "mode:text+markers" have the same issue. This error does not occur if type is defined as "scatter"

This did work in previous versions

### PR DESCRIPTION
**Pull request by emilykl**
Closes #7353 , #7441 

- The error was `Uncaught TypeError: systemFontKeywords.indexOf is not a function`
- This was due to a JSON file in the `css-system-font-keywords` (sub-)dependency not being included properly during the build process
- It turns out the build step where we strip out some metadata attributes (to reduce bundle size) was also inadvertently causing JSON files to be processed as JavaScript files, which resulted in them showing up 'blank' in the final build
- I've replaced that build step with a native ESBuild plugin with the same functionality
- This also allows us to remove one dev dependency, which is a nice bonus

Thanks to @ayjayt for helping diagnose and to @WeisSeb and @pawel-paciorek-at-metrohm for reporting.

## Minimal HTML/JS example demonstrating issue

(Based on @WeisSeb 's example in #7353)

```html
<!DOCTYPE html>
<html>
<head>
    <title>Scattergl empty</title>
    <script src="dist/plotly.js"></script>
</head>
<body>
    <div id="graph" style="width:600px;height:400px;"></div>
    <script>
        Plotly.newPlot('graph', [{
            type: 'scattergl',
            x: [1],
            y: [1],
            text: 'some text',
            mode: 'text+markers',
            textposition: 'top center',
        },]);
    </script>
</body>
</html>
```

Should look like:
Screenshot 2025-09-26 at 12 35 57 PM

## Steps for testing

1. Check out this branch
2. Run `npm i && npm run build`
3. Place the above HTML in a file in the root of your `plotly.js/` directory and visit in your browser
4. The chart should look like the image above

### CODE REVIEW

**Comment by emilykl** [comment]
Also should resolve https://github.com/plotly/plotly.py/issues/5336 but that won't be closed until this fix is included in Plotly.py.

File: tasks/compress_attributes.js
Comment (camdecoster) [inline tasks/compress_attributes.js:1]: Can you run the Biome formatter on this file with the following command?
```sh
npx @biomejs/biome format tasks/compress_attributes.js --write
```

File: tasks/compress_attributes.js [hunk 1]
```diff
@@ -35,22 +35,26 @@ function makeRegex(regexStr) {
...
+const allRegexes = [
+    makeStringRegex('description'),
+    makeJoinedArrayRegex('description'),
+    makeArrayRegex('requiredOpts'),
+    makeArrayRegex('otherOpts'),
+    makeStringRegex('role'),
+    makeStringRegex('hrName')
+];
+
+var esbuildPluginStripMeta = {
```
Comment (camdecoster) [inline tasks/compress_attributes.js]:
```suggestion
const esbuildPluginStripMeta = {
```

**Comment by emilykl** [comment]
Another bonus: Possibly reduces build time

(this is just one data point, wanted to do a sanity check to make sure it wasn't massively slower)

`time npm run build` on **master**
`npm run build  20.12s user 2.54s system 185% cpu 12.191 total`

`time npm run build` on **fix-missing-json-font-attrs**
`npm run build  13.88s user 1.99s system 131% cpu 12.086 total`

**Comment by gvwilson** [comment]
faster is gooder

**Comment by emilykl** [comment]
This bug should have been caught by the CI, but it turns out that we weren't actually running the `compress_attributes` step in the CI build process 🤦. So the build in the CI did not experience this issue. I've pushed [33c46a4](https://github.com/plotly/plotly.js/pull/7563/commits/33c46a45cb1a381317fbb6a5059d30684f9c5548) to fix that. 

(And the tests on [this branch I just created](https://github.com/plotly/plotly.js/compare/_scattergl_baseline_check) prove that _many_ baseline images fail to generate when we are using the correct build process in the CI.)

File: tasks/compress_attributes.js
Comment (emilykl) [reply tasks/compress_attributes.js:1]: done

**Comment by xzm9gqzc65-maker** [comment]
> Closes #7353 , #7441
> 
> * The error was `Uncaught TypeError: systemFontKeywords.indexOf is not a function`
> * This was due to a JSON file in the `css-system-font-keywords` (sub-)dependency not being included properly during the build process
> * It turns out the build step where we strip out some metadata attributes (to reduce bundle size) was also inadvertently causing JSON files to be processed as JavaScript files, which resulted in them showing up 'blank' in the final build
> * I've replaced that build step with a native ESBuild plugin with the same functionality
> * This also allows us to remove one dev dependency, which is a nice bonus
> 
> Thanks to @ayjayt for helping diagnose and to @WeisSeb and @pawel-paciorek-at-metrohm for reporting.
> 
> ## Minimal HTML/JS example demonstrating issue
> (Based on @WeisSeb 's example in #7353)
> 
> ```
> <!DOCTYPE html>
> <html>
> <head>
>     <title>Scattergl empty</title>
>     <script src="dist/plotly.js"></script>
> </head>
> <body>
>     <div id="graph" style="width:600px;height:400px;"></div>
>     <script>
>         Plotly.newPlot('graph', [{
>             type: 'scattergl',
>             x: [1],
>             y: [1],
>             text: 'some text',
>             mode: 'text+markers',
>             textposition: 'top center',
>         },]);
>     </script>
> </body>
> </html>
> ```
> 
> Should look like: Screenshot 2025-09-26 at 12 35 57 PM
> 
> ## Steps for testing
> 1. Check out this branch
> 2. Run `npm i && npm run build`
> 3. Place the above HTML in a file in the root of your `plotly.js/` directory and visit in your browser
> 4. The chart should look like the image above

_[](url)_
